### PR TITLE
Fixed serialisation bug

### PR DESCRIPTION
**Pull request by jmafoster1**
Fixed a problem with the `to_json` method of causal test result where pandas series weren't json serialisable. Now converting them to a dict.

### CODE REVIEW

**Comment by cwild-UoS** [comment]
According to the typing, `test_value.value` and the confidence intervals should be floats, which don't have a `to_dict()` method. 

What types are they in the scenario you are running?

**Comment by jmafoster1** [comment]
They are mostly floats, but are sometimes pandas `Series` objects. This happens when you have a treatment (or variables in the adjustment set) which are categorical. Then, instead of a float, you get a float for each value, which comes as a `Series`.

**Comment by cwild-UoS** [comment]
> Fixed a problem with the `to_json` method of causal test result where pandas series weren't json serialisable. Now converting them to a dict.

Ahh okay that makes sense. Sorry for more questions, but in your original comment you mention a `to_json` method. Where is this method? I wasn't aware we were serialising the `causal_test_result` objects

**Comment by jmafoster1** [comment]
Ah sorry, I think it's actually called `to_dict` in the `CausalTestResult` class (see Files Changed). I use it to serialise the causal test results to JSON so I can create a better log than the default one that I can just parse straight into my results processing program.

**Review by cwild-UoS — APPROVED** [review]

**Pull request merged**
