### PR TITLE
Fix minimal adjustment set

### LINKED ISSUE #90: Minimal Adjustment Sets
Used Dagitty to find the minimal adjustment set of the DAG we are using. Daggity said the minimal adjustment set for the node 'weight' was the node 'content', however the CTF said it was the node 'S3'.
`digraph DAG {
    rankdir=LR;
    content -> weight;
    weight -> S3;
    country -> S3;
    country -> distance;
    content -> S3;
    plane_transport -> S1;
    plane_transport -> S2;
    S1 -> alarm;
    S2 -> alarm;
    S3 -> alarm;
}
`
DAG from Daggity
image.

When we print out the Minimal Adjustment Set, it prints out both S3 and Content and it picks S3 as it is first. Daggity said the only one it should be is 'Content'.

### PR DESCRIPTION
**Pull request by jmafoster1**
Closes #90

### CODE REVIEW

**Comment by bobturneruk** [comment]
Can you run `black` to standardise formatting, please?

**Comment by jmafoster1** [comment]
Done. Sorry, I thought it did it automatically when you pushed. Is that a thing we can have it do?

**Comment by bobturneruk** [comment]
Yes - megalinter would need to make a commit here (you'd need to pull), or we could set it up as a pre-commit (which would run locally).

**Comment by jmafoster1** [comment]
Perhaps one to talk about in the next CITCoM update, unless one is objectively better than the other

**Review by AndrewC19 — APPROVED** [review]

**Pull request merged**
