### PR TITLE
Python 312 compatible

### PR DESCRIPTION
**Pull request by christopher-wild**
This PR  also removes the custom test helpers as they weren't best practise and aren't discoverable in the later python versions

### CODE REVIEW

**Comment by christopher-wild** [comment]
Also `CausalForestEstimator` is removed as it introduced the `econml` dependency which wasn't 3.11 or 3.12 compatible.

**Review by jmafoster1 — APPROVED** [review]

**Review by f-allian — CHANGES_REQUESTED** [review]
@christopher-wild All works well with 3.11, but have you tested these changes using 3.12? I'm getting a missing package error that seems to be due to a missing z3 dependency.

**Comment by christopher-wild** [comment]
> @christopher-wild All works well with 3.11, but have you tested these changes using 3.12? I'm getting a missing package error that seems to be due to a missing z3 dependency.

@f-allian, I did my testing in 3.12 and the CI tests for 3.12 pass for all OS's. Could you pop the steps you took to get the error in please?

**Comment by f-allian** [comment]
> > @christopher-wild All works well with 3.11, but have you tested these changes using 3.12? I'm getting a missing package error that seems to be due to a missing z3 dependency.
> 
> @f-allian, I did my testing in 3.12 and the CI tests for 3.12 pass for all OS's. Could you pop the steps you took to get the error in please?

I tested it using the DAFNI entry-point script. The unit tests also fail locally (see image below):

image

**Review by f-allian — APPROVED** [review]

**Pull request merged**
