### PR TITLE
Metamorphic relation and test generation from a DAG

### PR DESCRIPTION
**Pull request by AndrewC19**
This PR adds functionality for generating metamorphic relations from a causal DAG and support for generating metamorphic test cases for these metamorphic relations, if the variables involved are numerical.

### CODE REVIEW

**Review by jmafoster1 — COMMENTED** [review]
I'm a little worried that some of the lines in `MetamorphicRelation` are uncovered. I'm not a fan of writing tests just for the sake of it, but stuff like line 61 should probably be tested.
Also, @bobturneruk @cwild-UoS is there a way to get the abstract methods to pick up as covered if their concrete implementations are covered? We obviously can't test the pure abstract methods...

**Comment by bobturneruk** [comment]
@jmafoster1 - is the query above about testing ABCs still open? I've had a bit of a dig, and I'll come back with some info. if it's useful...

**Comment by jmafoster1** [comment]
@bobturneruk yes still an open question. I'm interested to hear what you've found.

**Comment by bobturneruk** [comment]
Would removing the ellipsis (not sure what the plural is) solve this adequately? I'm probably being too superficial.

**Comment by bobturneruk** [comment]
Probably doesn't need the ellipsis or `pass`.

**Comment by jmafoster1** [comment]
Will it not throw horrible syntax errors if you just leave the method entirely blank?

**Review by jmafoster1 — APPROVED** [review]

**Pull request merged**
