### PR TITLE
Revert "Formula validation"

### PR DESCRIPTION
**Pull request by f-allian**
Reverts CITCOM-project/CausalTestingFramework#235

### CODE REVIEW

**Comment by jmafoster1** [comment]
Does this take us back to 5.2.1? Is there really no other way than to undo everything? Presumably we can redo it again straight after?

**Comment by f-allian** [comment]
Reopening PR to merge the revert formula validation into main

**Comment by jmafoster1** [comment]
@f-allian, just to double check, is this the PR I need to approve to fix #238?

**Comment by f-allian** [comment]
@jmafoster1 It is, but I'm not sure if @cwild-UoS has any updates/anything to add to this? Reverting this PR is the only way I can think of that would allow you to push your changes without any merging problems

**Review by jmafoster1 — APPROVED** [review]

**Pull request merged**
